num1=eval(input("Enter First Number :"))
num2=eval(input("Enter Second Number :"))

print("Addition :",num1+num2)
print("Subtraction :",num1-num2)
print("multiplication :",num1*num2)
print("Division : %.2f"%(num1/num2))
print("Modulus : ",num1%num2)
print("Exponent :",num1**num2)
print("floor Division :",num1//num2)
